import { Arimo } from "next/font/google";
import Link from "next/link";

const arimo = Arimo({ subsets: ["latin"] });

const Footer = () => {
  return (
    <footer className={arimo.className}>
      <div>
        Data retrieved from <Link href="https://pokeapi.co/">Poké Api</Link>
      </div>
      <div>Logo and Sleepy Pikachu Image generated by Bing Image Creator</div>
      <div>All content trademarked by Nintendo</div>
    </footer>
  );
};

export default Footer;
